
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tax_compliance_db
    environment:
      POSTGRES_DB: tax_compliance_hub
      POSTGRES_USER: tax_admin
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - tax_compliance_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tax_admin -d tax_compliance_hub"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tax_compliance_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@audit.ke
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tax_compliance_network
    restart: unless-stopped
    depends_on:
      - postgres

  app:
    build: .
    container_name: tax_compliance_app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://tax_admin:secure_password_123@postgres:5432/tax_compliance_hub
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-super-secret-key-here
      NEXTCLOUD_URL: https://cloud.audit.ke
      NEXTCLOUD_USERNAME: it@csa.co.ke
      NEXTCLOUD_PASSWORD: Wakatiimefika@1998
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - tax_compliance_network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: tax_compliance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tax_compliance_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: tax_compliance_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - tax_compliance_network
    restart: unless-stopped
    depends_on:
      - app

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  tax_compliance_network:
    driver: bridge
